version: "3.1"
language: en
pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LexicalSyntacticFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "RegexEntityExtractor"
  case_sensitive: true
  use_lookup_tables: true
  use_regexes: true
  use_word_boundaries: false
- name: "DIETClassifier"
  epochs: 100
- name: "EntitySynonymMapper"
- name: "ResponseSelector"
  epochs: 100
- name: "FallbackClassifier"
  threshold: 0.3
  nlu_threshold: 0.3
- name: "DucklingEntityExtractor"
  url: "http://duckling_server:8000"
  dimensions:
  - time
  - duration
  - number
  - amount-of-money
  - temperature
  - distance
policies:
- name: "MemoizationPolicy"
- name: "RulePolicy"
- name: "UnexpecTEDIntentPolicy"
  max_history: 5
  epochs: 100
- name: "TEDPolicy"
  max_history: 5
  epochs: 100
assistant_id: 20250919-015501-universal-conference
